services:
  - type: web
    name: go-backend-api
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    region: singapore # หรือ oregon, frankfurt
    healthCheckPath: /health